-- 创建一定会命中规则的测试报销单
-- 规则：办公用品单次限额1000元
-- 条件：发票金额 > 1000 AND 发票子分类 = 办公用品

-- 1. 创建测试报销单
INSERT INTO reimbursements (
  id, user_id, user_name, department, applicant_level, type, title, description,
  total_amount, currency, apply_date, expense_date, start_date, end_date,
  destination, city, province, travel_reason, transportation, project_code,
  budget_code, approval_required, approved_by, approved_at, audit_id, status,
  created_at, updated_at
) VALUES (
  'test-reimbursement-002',
  '550e8400-e29b-41d4-a716-446655440002',
  '测试用户',
  '技术部',
  '普通员工',
  '办公用品',
  '办公用品采购',
  '购买办公用品测试',
  1500.00,
  'CNY',
  NOW(),
  NOW(),
  NULL,
  NULL,
  NULL,
  '北京',
  '北京',
  '日常办公',
  NULL,
  'PROJ-001',
  'BUDGET-001',
  false,
  '',
  NULL,
  '',
  'pending_submission',
  NOW(),
  NOW()
);

-- 2. 创建测试发票 - 一定会命中"办公用品单次限额1000元"规则
INSERT INTO invoices (
  id, reimbursement_id, type, code, number, date, amount, tax_amount,
  payer, payee, buyer_name, buyer_tax_no, seller_name, seller_tax_no,
  commodity_name, specification, unit, quantity, price, image_path,
  ocr_result, items, total_items, main_commodity, status, category,
  sub_category, expense_type, payment_method, location, city, province,
  country, purpose, description, project_code, department_code, cost_center,
  contract_number, approval_level, is_reimbursable, is_personal, is_vat,
  vat_rate, exchange_rate, original_amount, original_currency, receipt_number,
  invoice_series, batch_number, valid_from, valid_to, is_electronic,
  is_duplicate, related_invoice_id, verification_status, remarks, created_at, updated_at
) VALUES (
  'test-invoice-002',
  'test-reimbursement-002',
  '增值税普通发票',
  '1234567890',
  '98765432',
  '2026-03-01',
  1500.00,
  0.00,
  '张三',
  '办公用品商店',
  '张三',
  '91310000XXXXXXXXXX',
  '办公用品商店',
  '91310000YYYYYYYYYY',
  '办公设备',
  '笔记本电脑',
  '台',
  1.00,
  1500.00,
  '/uploads/invoices/test-invoice-002.jpg',
  NULL,
  NULL,
  1,
  '办公设备',
  'verified',
  '办公用品',
  '办公用品',
  '办公用品',
  '公司账户',
  '北京',
  '北京',
  '北京',
  'China',
  '购买办公用品',
  '购买笔记本电脑',
  'PROJ-001',
  'DEPT-001',
  'COST-001',
  'CONTRACT-001',
  'manager',
  1,
  0,
  0,
  0.00,
  1.0000,
  1500.00,
  'CNY',
  'REC-002',
  'SERIES-002',
  'BATCH-002',
  '2026-03-01',
  '2026-12-31',
  0,
  0,
  NULL,
  'verified',
  '测试发票 - 应该命中办公用品限额规则',
  NOW(),
  NOW()
);
