-- 插入符合标准的交通费测试数据
-- 普通员工高铁限额是500元，我们使用400元

INSERT INTO reimbursements (
  id, user_id, user_name, department, applicant_level, type, title, description,
  total_amount, currency, apply_date, expense_date, start_date, end_date,
  destination, city, province, travel_reason, transportation, project_code,
  budget_code, approval_required, approved_by, approved_at, audit_id, status,
  created_at, updated_at
) VALUES (
  'test-reimbursement-004',
  '550e8400-e29b-41d4-a716-446655440002',
  '测试用户',
  '技术部',
  '普通员工',
  '交通费',
  '交通费报销',
  '高铁票报销',
  400.00,
  'CNY',
  NOW(),
  NOW(),
  '2026-03-10',
  '2026-03-12',
  '北京',
  '北京',
  '北京',
  '参加技术会议',
  '高铁',
  'PROJ-001',
  'BUDGET-001',
  false,
  '',
  NULL,
  '',
  'pending_submission',
  NOW(),
  NOW()
)
ON DUPLICATE KEY UPDATE total_amount=VALUES(total_amount);

INSERT INTO invoices (
  id, reimbursement_id, type, code, number, date, amount, tax_amount,
  payer, payee, buyer_name, buyer_tax_no, seller_name, seller_tax_no,
  commodity_name, specification, unit, quantity, price, image_path,
  ocr_result, items, total_items, main_commodity, status,
  created_at, updated_at, category, sub_category, expense_type,
  payment_method, merchant_type, merchant_code, location, city, province,
  country, purpose, description, project_code, department_code,
  cost_center, contract_number, approval_level, is_reimbursable,
  is_personal, is_vat, vat_rate, exchange_rate, original_amount,
  original_currency, receipt_number, invoice_series, batch_number,
  valid_from, valid_to, is_electronic, is_duplicate, related_invoice_id,
  verification_status, verification_time, remarks
) VALUES (
  'test-invoice-004',
  'test-reimbursement-004',
  '增值税普通发票',
  '1234567891',
  '98765434',
  '2026-03-01',
  400.00,
  0,
  '张三',
  '中国铁路北京局',
  '张三',
  '91310000XXXXXXXXXX',
  '中国铁路北京局',
  '91310000YYYYYYYYYY',
  '高铁票',
  '二等座',
  '张',
  1,
  400,
  '/uploads/invoices/test-invoice-004.jpg',
  '',
  '',
  1,
  '高铁票',
  'verified',
  NOW(),
  NOW(),
  '交通费',
  '差旅交通',
  '差旅费',
  '公司账户',
  '',
  '',
  '北京',
  '北京',
  '北京',
  'China',
  '北京出差交通费',
  '高铁往返北京上海',
  'PROJ-001',
  'DEPT-001',
  'COST-001',
  'CONTRACT-001',
  'manager',
  true,
  false,
  false,
  0,
  1,
  400,
  'CNY',
  'REC-004',
  'SERIES-004',
  'BATCH-004',
  '2026-03-01',
  '2026-12-31',
  false,
  false,
  '',
  'verified',
  NULL,
  '测试发票 - 交通费（符合标准）'
)
ON DUPLICATE KEY UPDATE amount=VALUES(amount);
