-- 创建交通费测试数据
-- 规则：交通费校验规则
-- 条件：feat-transportation == false

-- 1. 创建测试报销单
INSERT INTO reimbursements (
  id, user_id, user_name, department, applicant_level, type, title, description,
  total_amount, currency, apply_date, expense_date, start_date, end_date,
  destination, city, province, travel_reason, transportation, project_code,
  budget_code, approval_required, approved_by, approved_at, audit_id, status,
  created_at, updated_at
) VALUES (
  'test-reimbursement-003',
  '550e8400-e29b-41d4-a716-446655440002',
  '测试用户',
  '技术部',
  '普通员工',
  '交通费',
  '交通费报销',
  '高铁票报销',
  800.00,
  'CNY',
  NOW(),
  NOW(),
  '2026-03-10',
  '2026-03-12',
  '北京',
  '北京',
  '北京',
  '参加技术会议',
  '高铁',
  'PROJ-001',
  'BUDGET-001',
  false,
  '',
  NULL,
  '',
  'pending_submission',
  NOW(),
  NOW()
);

-- 2. 创建测试发票 - 交通费
INSERT INTO invoices (
  id, reimbursement_id, type, code, number, date, amount, tax_amount,
  payer, payee, buyer_name, buyer_tax_no, seller_name, seller_tax_no,
  commodity_name, specification, unit, quantity, price, image_path,
  ocr_result, items, total_items, main_commodity, status, category,
  sub_category, expense_type, payment_method, location, city, province,
  country, purpose, description, project_code, department_code, cost_center,
  contract_number, approval_level, is_reimbursable, is_personal, is_vat,
  vat_rate, exchange_rate, original_amount, original_currency, receipt_number,
  invoice_series, batch_number, valid_from, valid_to, is_electronic,
  is_duplicate, related_invoice_id, verification_status, remarks, created_at, updated_at
) VALUES (
  'test-invoice-003',
  'test-reimbursement-003',
  '增值税普通发票',
  '1234567890',
  '98765433',
  '2026-03-01',
  800.00,
  0.00,
  '张三',
  '中国铁路北京局',
  '张三',
  '91310000XXXXXXXXXX',
  '中国铁路北京局',
  '91310000YYYYYYYYYY',
  '高铁票',
  '二等座',
  '张',
  2.00,
  400.00,
  '/uploads/invoices/test-invoice-003.jpg',
  NULL,
  NULL,
  1,
  '高铁票',
  'verified',
  '交通费',
  '差旅交通',
  '差旅费',
  '公司账户',
  '北京',
  '北京',
  '北京',
  'China',
  '北京出差交通费',
  '高铁往返北京上海',
  'PROJ-001',
  'DEPT-001',
  'COST-001',
  'CONTRACT-001',
  'manager',
  1,
  0,
  0,
  0.00,
  1.0000,
  800.00,
  'CNY',
  'REC-003',
  'SERIES-003',
  'BATCH-003',
  '2026-03-01',
  '2026-12-31',
  0,
  0,
  NULL,
  'verified',
  '测试发票 - 交通费',
  NOW(),
  NOW()
);
